import { BadgeDefinition } from '../education/types';

export const ALL_BADGE_DEFINITIONS: BadgeDefinition[] = [
  // Tier Badges
  {
    id: 'badge_tier_bronze',
    name: 'Bronze Safety Advocate',
    category: 'TIER',
    level: 'BRONZE',
    description: 'Awarded for initiating active participation in community safety awareness and verified early warning alerts.',
    iconName: 'award',
    criteriaExplanation: 'Requires 2+ verified community events (e.g. verified reports, campaign participation).',
    requiredVerifiedEventsCount: 2,
    badgeGradient: 'from-amber-900 via-amber-950 to-slate-900',
    borderColor: 'border-amber-600/80',
  },
  {
    id: 'badge_tier_silver',
    name: 'Silver Safety Guardian',
    category: 'TIER',
    level: 'SILVER',
    description: 'Awarded for sustained, verified contributions to neighborhood hazard mitigation and anti-mob justice education.',
    iconName: 'star',
    criteriaExplanation: 'Requires 5+ verified community events and active campaign involvement.',
    requiredVerifiedEventsCount: 5,
    badgeGradient: 'from-slate-400 via-slate-700 to-slate-900',
    borderColor: 'border-slate-300/80',
  },
  {
    id: 'badge_tier_gold',
    name: 'Gold Peace Standard',
    category: 'TIER',
    level: 'GOLD',
    description: 'Distinguished tier awarded to pillar members demonstrating exemplary leadership in non-confrontational community protection.',
    iconName: 'crown',
    criteriaExplanation: 'Requires 10+ verified events, including early warning confirmations and campaign organization.',
    requiredVerifiedEventsCount: 10,
    badgeGradient: 'from-amber-400 via-yellow-600 to-amber-950',
    borderColor: 'border-amber-400/90',
  },

  // Specialized Badges
  {
    id: 'badge_spec_guardian',
    name: 'Community Guardian',
    category: 'SPECIALIZED',
    level: 'SPECIALIST',
    description: 'Awarded for submitting 3+ verified early warning reports confirmed by leaders or authorities. Raw unverified submissions do not count.',
    iconName: 'shield-check',
    criteriaExplanation: '3+ verified incident reports confirmed by authority or community leaders.',
    requiredVerifiedEventsCount: 3,
    badgeGradient: 'from-blue-900 via-indigo-950 to-slate-900',
    borderColor: 'border-blue-500/80',
  },
  {
    id: 'badge_spec_early_warning',
    name: 'Early Warning Specialist',
    category: 'SPECIALIZED',
    level: 'SPECIALIST',
    description: 'Awarded for providing rapid, verified notice of high-danger safety hazards, preventing potential crowd bottlenecks or violence.',
    iconName: 'alert-triangle',
    criteriaExplanation: '2+ confirmed high-danger early warning reports.',
    requiredVerifiedEventsCount: 2,
    badgeGradient: 'from-red-900 via-amber-950 to-slate-900',
    borderColor: 'border-red-500/80',
  },
  {
    id: 'badge_spec_builder',
    name: 'Community Builder',
    category: 'SPECIALIZED',
    level: 'SPECIALIST',
    description: 'Awarded for expanding the trusted neighborhood safety network by inviting verified community members who actively participate.',
    iconName: 'users',
    criteriaExplanation: '5+ verified member invitations resulting in active safety participation.',
    requiredVerifiedEventsCount: 5,
    badgeGradient: 'from-emerald-900 via-teal-950 to-slate-900',
    borderColor: 'border-emerald-500/80',
  },
  {
    id: 'badge_spec_campaign_leader',
    name: 'Campaign Leader',
    category: 'SPECIALIZED',
    level: 'SPECIALIST',
    description: 'Awarded for organizing and successfully completing an anti-jungle justice or community safety awareness campaign.',
    iconName: 'megaphone',
    criteriaExplanation: '1+ completed community educational campaign organized.',
    requiredVerifiedEventsCount: 1,
    badgeGradient: 'from-purple-900 via-indigo-950 to-slate-900',
    borderColor: 'border-purple-500/80',
  },
  {
    id: 'badge_spec_life_saver',
    name: 'Life Saver',
    category: 'SPECIALIZED',
    level: 'SPECIALIST',
    description: 'Awarded when an early warning alert directly leads to emergency authority intervention that defuses imminent mob violence.',
    iconName: 'heart-handshake',
    criteriaExplanation: '1+ authority-acknowledged emergency escalation that prevented extrajudicial harm.',
    requiredVerifiedEventsCount: 1,
    badgeGradient: 'from-pink-900 via-rose-950 to-slate-900',
    borderColor: 'border-pink-500/80',
  },
];
